// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxuwjwutmnupqitnsray.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dXdqd3V0bW51cHFpdG5zcmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTk2OTYsImV4cCI6MjA2MTUzNTY5Nn0.YbKfQCKjuLXN-NrK_EmyO8TkYidszzH6xufAhIyDzrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);